# Generated by Django 5.2.3 on 2025-07-23 11:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('pop3_server', models.CharField(max_length=255)),
                ('pop3_port', models.IntegerField(default=995)),
                ('smtp_server', models.CharField(max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('use_ssl', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('recipients', models.TextField()),
                ('cc', models.TextField(blank=True)),
                ('bcc', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('date_received', models.DateTimeField(default=django.utils.timezone.now)),
                ('read', models.BooleanField(default=False)),
                ('flagged', models.BooleanField(default=False)),
                ('replied', models.BooleanField(default=False)),
                ('forwarded', models.BooleanField(default=False)),
                ('size', models.IntegerField(default=0)),
                ('uid', models.CharField(blank=True, max_length=255, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='djmail.emailaccount')),
            ],
            options={
                'ordering': ['-date_received'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('file', models.FileField(upload_to='email_attachments/%Y/%m/')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='djmail.email')),
            ],
        ),
        migrations.CreateModel(
            name='EmailFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('folder_type', models.CharField(choices=[('inbox', 'Inbox'), ('sent', 'Sent'), ('drafts', 'Drafts'), ('outbox', 'Outbox'), ('trash', 'Trash'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='djmail.emailaccount')),
            ],
            options={
                'unique_together': {('account', 'folder_type')},
            },
        ),
        migrations.AddField(
            model_name='email',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='djmail.emailfolder'),
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djmail.emailtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('deferred', 'Deferred')], default='not_started', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('related_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='djmail.email')),
            ],
        ),
        migrations.CreateModel(
            name='EmailAccountAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('read', 'Read Only'), ('full', 'Full Access')], default='read', max_length=10)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this access grant')),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='djmail.emailaccount')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_accesses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_account_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Account Access',
                'verbose_name_plural': 'Email Account Accesses',
                'unique_together': {('user', 'email_account')},
            },
        ),
        migrations.CreateModel(
            name='EmailServerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('send', 'Email Sent'), ('receive', 'Email Received'), ('smtp_connect', 'SMTP Connection'), ('smtp_auth', 'SMTP Authentication'), ('smtp_command', 'SMTP Command'), ('smtp_response', 'SMTP Response'), ('smtp_error', 'SMTP Error'), ('imap_connect', 'IMAP Connection'), ('imap_auth', 'IMAP Authentication'), ('imap_command', 'IMAP Command'), ('imap_response', 'IMAP Response'), ('imap_error', 'IMAP Error'), ('system', 'System Log')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('to_email', models.TextField(blank=True)),
                ('server_host', models.CharField(blank=True, max_length=255)),
                ('server_port', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, max_length=10)),
                ('command', models.TextField(blank=True)),
                ('response', models.TextField(blank=True)),
                ('response_code', models.CharField(blank=True, max_length=10)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_logs', to='djmail.email')),
                ('email_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_logs', to='djmail.emailaccount')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_server_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Server Log',
                'verbose_name_plural': 'Email Server Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='djmail_emai_timesta_98487a_idx'), models.Index(fields=['log_type'], name='djmail_emai_log_typ_28cd79_idx'), models.Index(fields=['status'], name='djmail_emai_status_c401f7_idx'), models.Index(fields=['email_account'], name='djmail_emai_email_a_f970b8_idx'), models.Index(fields=['user'], name='djmail_emai_user_id_1200d7_idx'), models.Index(fields=['session_id'], name='djmail_emai_session_78940b_idx')],
            },
        ),
    ]
