# Generated by Django 5.2.3 on 2025-07-23 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=3306)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Database Server',
                'verbose_name_plural': 'Database Servers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReplicationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('databases', models.JSONField(help_text='List of databases to replicate')),
                ('status', models.CharField(choices=[('pending', 'Pending Setup'), ('configuring_source', 'Configuring Source'), ('waiting_source_config', 'Waiting for Source Configuration'), ('dumping_data', 'Dumping Source Data'), ('importing_data', 'Importing to Target'), ('configuring_target', 'Configuring Target'), ('starting_replication', 'Starting Replication'), ('active', 'Active'), ('error', 'Error'), ('stopped', 'Stopped')], default='pending', max_length=50)),
                ('lag_seconds', models.IntegerField(default=0)),
                ('replication_user', models.CharField(blank=True, max_length=100)),
                ('replication_password', models.CharField(blank=True, max_length=255)),
                ('server_id_source', models.IntegerField(blank=True, null=True)),
                ('server_id_target', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('setup_step', models.IntegerField(default=1)),
                ('setup_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_replications', to='djsql.databaseserver')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_replications', to='djsql.databaseserver')),
            ],
            options={
                'ordering': ['source__name', 'target__name'],
                'unique_together': {('source', 'target')},
            },
        ),
        migrations.CreateModel(
            name='ReplicationSetupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('step', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('is_error', models.BooleanField(default=False)),
                ('command_to_run', models.TextField(blank=True)),
                ('requires_user_action', models.BooleanField(default=False)),
                ('user_action_completed', models.BooleanField(default=False)),
                ('replication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_logs', to='djsql.replicationlink')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('host', models.CharField(default='%', max_length=255)),
                ('user_type', models.CharField(choices=[('admin', 'Administrator'), ('repl', 'Replication User'), ('app', 'Application User')], max_length=20)),
                ('privileges', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='djsql.databaseserver')),
            ],
            options={
                'verbose_name': 'Database User',
                'verbose_name_plural': 'Database Users',
                'ordering': ['server', 'username', 'host'],
                'unique_together': {('server', 'username', 'host')},
            },
        ),
    ]
