"""
Django settings for djcoop project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=r%4bu6c12j1c@%h--l#w6px3x_e^====sq2tme@f1rq5y#z6o'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG=True is acceptable for beta but MUST be disabled before production use
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required for allauth

    # Third party apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # Optional: Add social providers
    # 'allauth.socialaccount.providers.google',
    # 'allauth.socialaccount.providers.github',

    # Local apps
    'core.apps.CoreConfig',
    'core.templatetags',
    'djmail.apps.DjmailConfig',
    'djsql.apps.DjsqlConfig',
    'djnote.apps.DjnoteConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Required for allauth
]

ROOT_URLCONF = 'djcoop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Add project-level templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djcoop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# MySQL Connection Settings for Remote Hosts
MYSQL_CHARSET = 'utf8mb4'
MYSQL_COLLATION = 'utf8mb4_unicode_ci'


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (Uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email logging settings (define before LOGGING)
EMAIL_LOG_LEVEL = 'DEBUG'  # Log all email communications
EMAIL_LOG_FILE = BASE_DIR / 'logs' / 'email.log'
EMAIL_LOG_MAX_SIZE = 10 * 1024 * 1024  # 10MB
EMAIL_LOG_BACKUP_COUNT = 5

# Mail operations logging
MAIL_OPERATIONS_LOG = BASE_DIR / 'logs' / 'mail_operations.log'
MAIL_ERRORS_LOG = BASE_DIR / 'logs' / 'mail_errors.log'
MAIL_FETCH_LOG = BASE_DIR / 'logs' / 'mail_fetch.log'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'email_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': EMAIL_LOG_FILE,
            'maxBytes': EMAIL_LOG_MAX_SIZE,
            'backupCount': EMAIL_LOG_BACKUP_COUNT,
            'formatter': 'verbose',
        },
        'email_console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'mail_operations_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': MAIL_OPERATIONS_LOG,
            'maxBytes': EMAIL_LOG_MAX_SIZE,
            'backupCount': EMAIL_LOG_BACKUP_COUNT,
            'formatter': 'verbose',
        },
        'mail_errors_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': MAIL_ERRORS_LOG,
            'maxBytes': EMAIL_LOG_MAX_SIZE,
            'backupCount': EMAIL_LOG_BACKUP_COUNT,
            'formatter': 'verbose',
        },
        'mail_fetch_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': MAIL_FETCH_LOG,
            'maxBytes': EMAIL_LOG_MAX_SIZE,
            'backupCount': EMAIL_LOG_BACKUP_COUNT,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'core': {  # This is your app name
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'djmail': {  # Mail app logging
            'handlers': ['console', 'email_file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'djmail.email': {  # Email-specific logging
            'handlers': ['email_console', 'email_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'djmail.smtp': {  # SMTP communication logging
            'handlers': ['email_console', 'email_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'mail_operations': {  # General mail operations
            'handlers': ['console', 'mail_operations_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'mail_errors': {  # Mail operation errors
            'handlers': ['console', 'mail_errors_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'mail_fetch': {  # Mail fetching operations
            'handlers': ['console', 'mail_fetch_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# =============================================================================
# DJANGO ALLAUTH CONFIGURATION
# =============================================================================

# Required for allauth
SITE_ID = 1

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Default Django auth
    'allauth.account.auth_backends.AuthenticationBackend',  # Allauth
]

# Allauth settings (updated format)
ACCOUNT_LOGIN_METHODS = {'email'}  # Use email instead of username
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']  # Required signup fields
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Disable email verification for development
ACCOUNT_RATE_LIMITS = {
    'login_failed': '5/5m',  # 5 attempts per 5 minutes
}
ACCOUNT_LOGOUT_ON_GET = True  # Allow logout via GET request
ACCOUNT_SESSION_REMEMBER = True  # Remember login sessions

# Email settings for verification (development)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Print emails to console
# For production, use SMTP:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-app-password'



# Login/Logout URLs
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/mail/'  # Redirect to mail interface after login
LOGOUT_REDIRECT_URL = '/'  # Redirect to home after logout

# Account forms (optional customization)
# ACCOUNT_FORMS = {
#     'signup': 'core.forms.CustomSignupForm',
# }
