# Generated by Django 5.1.3 on 2025-02-16 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='replicationlink',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='replicationlink',
            name='replication_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='replicationlink',
            name='replication_user',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='replicationlink',
            name='server_id_source',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replicationlink',
            name='server_id_target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replicationlink',
            name='setup_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='replicationlink',
            name='setup_step',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='replicationlink',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Setup'), ('configuring_source', 'Configuring Source'), ('waiting_source_config', 'Waiting for Source Configuration'), ('dumping_data', 'Dumping Source Data'), ('importing_data', 'Importing to Target'), ('configuring_target', 'Configuring Target'), ('starting_replication', 'Starting Replication'), ('active', 'Active'), ('error', 'Error'), ('stopped', 'Stopped')], default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='ReplicationSetupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('step', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('is_error', models.BooleanField(default=False)),
                ('command_to_run', models.TextField(blank=True)),
                ('requires_user_action', models.BooleanField(default=False)),
                ('user_action_completed', models.BooleanField(default=False)),
                ('replication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_logs', to='djsql.replicationlink')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
