# Generated by Django 5.1.3 on 2025-02-23 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_replicationlink_error_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='databaseserver',
            options={'ordering': ['name'], 'verbose_name': 'Database Server', 'verbose_name_plural': 'Database Servers'},
        ),
        migrations.AddField(
            model_name='databaseserver',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='databaseserver',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='databaseserver',
            name='port',
            field=models.IntegerField(default=3306),
        ),
        migrations.CreateModel(
            name='DatabaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('host', models.CharField(default='%', max_length=255)),
                ('user_type', models.CharField(choices=[('admin', 'Administrator'), ('repl', 'Replication User'), ('app', 'Application User')], max_length=20)),
                ('privileges', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.databaseserver')),
            ],
            options={
                'verbose_name': 'Database User',
                'verbose_name_plural': 'Database Users',
                'ordering': ['server', 'username', 'host'],
                'unique_together': {('server', 'username', 'host')},
            },
        ),
    ]
