# Generated by Django 5.2 on 2025-06-18 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_databaseserver_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='replicationlink',
            unique_together=set(),
        ),
    ]
