# Generated by Django 5.2 on 2025-06-18 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_replicationlink_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='replicationlink',
            unique_together={('source', 'target')},
        ),
    ]
