# Generated by Django 5.2 on 2025-06-18 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_replicationlink_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatabaseUser',
        ),
        migrations.DeleteModel(
            name='DatabaseServer',
        ),
        migrations.DeleteModel(
            name='ReplicationLink',
        ),
        migrations.DeleteModel(
            name='ReplicationSetupLog',
        ),
    ]
