# Generated by Django 5.2.3 on 2025-07-23 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('scan_type', models.CharField(choices=[('document', 'Document'), ('note', 'Note')], default='note', max_length=20)),
                ('document_id', models.CharField(blank=True, help_text='Auto-generated ID for documents', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retention_days', models.PositiveIntegerField(blank=True, help_text='How many days to keep this document (only for documents)', null=True)),
                ('due_date', models.DateTimeField(blank=True, help_text='When this document should be deleted', null=True)),
                ('description', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='scans/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='scans/thumbnails/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_text', models.TextField(blank=True, help_text='OCR extracted text')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='djnote.scan')),
            ],
            options={
                'ordering': ['page_number'],
                'unique_together': {('scan', 'page_number')},
            },
        ),
    ]
